DjangoAdmin/urls.py
from django.contrib import admin
from django.urls import path,include
from VideoApp.urls import views


urlpatterns = [
    path('',views.index,name='index'),
    path('VideoApp/',include('VideoApp.urls')),
    path('admin/', admin.site.urls),
]

VideoApp/urls.py
from VideoApp import views
from django.urls import path

#template tagging global variable app_name

app_name='VideoApp'


urlpatterns = [
    path('other/',views.other,name='other'),
    path('relative/',views.relative_urls,name='relative'),
]

VideoApp/models.py
from django.db import models
# Create your models here.

class Movies(models.Model):
    title=models.CharField(max_length=256)
    length=models.PositiveIntegerField()
    release_year=models.PositiveIntegerField()

    def __str__(self):
        return self.title

class Customer(models.Model):
    first_name=models.CharField(max_length=256)
    last_name=models.CharField(max_length=256)
    phone_number=models.PositiveIntegerField()

    def __str__(self):
        return self.first_name+' '+self.last_name

VideoApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    my_dict={'text':'capitalize me','number':150}
    return render(request,'VideoApp/index.html',context=my_dict)

def other(request):
    return render(request,'VideoApp/other.html')

def relative_urls(request):
    return render(request,'VideoApp/relative_urls.html')

templates/VideoApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base page</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
      <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' % }">BRAND</a></li>
          <li><a class="navbar-link"  href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class="navbar-link"  href="{% url 'VideoApp:other' %}">Other</a></li>
        </ul>
      </div>
      </nav>
      <div class="container">
      {% block body_block %}
         <!--anything outside this will be inherited if u extend-->
      {% endblock %}
      </div>
  </body>
</html>

templates/VideoApp/index.html
<!DOCTYPE html>
{%  extends 'VideoApp/base.html' %}
{% load my_custom_filters %}
{% block body_block %}
    <h1>Welcome to index page</h1>
    <h2>This is an example of Template inheritance</h2>
<!-- examples of built in template filters -->
    <h2>{{text|title}}</h2>
    <h3>{{text|upper}}</<h3>
    <h3>{{number|add:'35'}}</h3>
<!-- examples of custom template filters -->
    <h2>{{text|cutfilter:'me'}}</h2>
    <h2>{{text|splitfilter}}
{% endblock %}

templates/VideoApp/other.html
<!DOCTYPE html>
{% extends "VideoApp/base.html" %}
  {% block body_block %}
    <h1>Welcome to other page</h1>
  {% endblock %}

templates/VideoApp/relative_urls.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Relative URL page</title>
  </head>
  <body>
    <h1>Welcome to Relative Urls template</h1>
<!--instead of href=VideoApp/other.html" hard coding we use relative url -->
    <a href="{% url 'VideoApp:other' %}">Go to others page</a>
    <a href="{% url 'VideoApp:relative' %}">Go to Relative Urls page</a>
    <a href="{% url 'index' %}">Go to index page</a>
    <a href="{% url 'admin:index' %}">Go to admin</a>
  </body>
</html>